import type { NextPage } from 'next'
import Head from 'next/head'
import { Form, Col, Button, Stack } from "react-bootstrap";


const Home: React.FC  = () => {
  return (
    <div>
      <Head>
        <title>WEG AT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <a href='/cadastro/registro'>cadastro</a>
    </div>
  )
}

export default Home
